name: Blog Post
description: File a bug report.
title: "[BLOG] "
labels: ["wg-comms/blog", "issue/needs-triage", "board/wg-comms"]
projects: ["cncf/10"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the TAG! Please use this issue template only if you are planning to write a blog post for the TAG Environmental Sustainability. The blog can be found here: https://tag-env-sustainability.cncf.io/blog/.
  - type: input
    id: blog-details
    attributes:
      label: Blog and Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: blog-abstract
    attributes:
      label: Abstract
      description: Please summarize what this blog post is about
    validations:
      required: true
  - type: textarea
    id: blog-scope
    attributes:
      label: Scope
      description: Please summarize the scope of the blog post
    validations:
      required: true
  - type: textarea
    id: blog-expected-audience
    attributes:
      label: Expected audience
      description: Please summarize the expected audience of the blog post
    validations:
      required: true
  - type: textarea
    id: blog-goals-and-non-goals
    attributes:
      label: Goals and Non Goals
      description: Please summarize the goals of the blog post
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.cncf.io/conduct/). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: tasks
    attributes:
      label: 🖱️Tasks
      value: |
        - [ ] Outline Blog post
          - [ ] [**Author**] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
          - [ ] [**Author**] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
          - [ ] [**TAG ENV Lead**] One of the TAG ENV leads assigned themselves to wrangle the blog
          - [ ] [**TAG ENV Lead**] Blog post outline and theme has been discussed
        - [ ] [**Author**] Blog post written and ready for review
        - [ ] Review
          - [ ] [**Author**] blog post PR opened (blog posts are added to the [`website/content/en/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/blog) folder for English content, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
          - [ ] [**Author**] notified TAG ENV community for review via Slack on the `tag-env-sustainability` channel.
          - [ ] [**Author**] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
          - [ ] [**Author**] Feedback and comments have been resolved.
          - [ ] [**Reviewers**] reviewed blog post.
          - [ ] [**TAG ENV Lead**] reviewed blog post.
          - [ ] [**TAG ENV Lead**] ready to get published.
          - [ ] [**TAG ENV Lead**] notified one of the ToC liaisons to sign off the blog post.
          - [ ] [**TAG ENV ToC Liaison**] reviewed blog post.
          - [ ] [**TAG ENV Lead**] merged blog post.
          - [ ] *optional* [**TAG ENV Lead**] schedule the blog post on the CNCF blog next to the TAG ENV blog
          - [ ] [**Author**] Wrote feedback about the blog post process as a comment under this issue
  - type: textarea
    id: blog-scope
    attributes:
      label: Comments
      description: Space to add any other comments about the blog post
      placeholder: None
